### ISSUE TITLE
Keynote dropdown under Speaker has a weird blue background 

### ISSUE THREAD

**Issue by varundey** [pythonindia/inpycon2018#185] opened 2018-09-12 07:45 UTC
<img width="1439" alt="screen shot 2018-09-12 at 1 12 55 pm" src="https://user-images.githubusercontent.com/9202135/45409712-94545980-b68d-11e8-9d08-f00860ff778b.png">
 Click on Speakers and then click on Keynotes. It shows a weird blue background color for the list item that does not go with the theme.

**Comment by varundey** [comment] 2018-09-12 07:45
I would like to take it up. #dibs

**Comment by ananyo2012** [comment] 2018-09-12 08:18
@varundey Can you try doing a hard reload ?

**Comment by varundey** [comment] 2018-09-12 08:32
@ananyo2012 i tried loading in firefox private window with cache disabled. issue still persists

**Comment by varundey** [comment] 2018-09-12 10:51
Tickets section has the same issue. Debugged and seems to be coming from Bootstrap CSS. 
<img width="1439" alt="screen shot 2018-09-12 at 1 12 55 pm" src="https://user-images.githubusercontent.com/9202135/45413940-f0bc7680-b697-11e8-8538-f502f0745150.png">

**Comment by bhansa** [comment] 2018-09-12 12:50
@varundey Is it browser specific? Are you able to reproduce the same in Chrome as well?

**Comment by varundey** [comment] 2018-09-12 17:16
@bhansa yep!
<img width="1373" alt="screen shot 2018-09-12 at 10 46 59 pm" src="https://user-images.githubusercontent.com/9202135/45441776-9e9e4400-b6dd-11e8-93ca-e306140fa212.png">

**Comment by ananyo2012** [comment] 2018-09-13 08:17
I still can't reproduce the issue. I checked in 3 browsers Chrome canary v71, Firefox Quantum v62 and Microsoft edge v38. @pythonindia/pycon-2018-team Can others verify in their browsers ?

**Comment by realslimshanky** [comment] 2018-09-13 08:38
@ananyo2012 @bhansa maybe it's a platform/browser issue of some sort. If @varundey is getting the effect may be more folks can also see the same. So, it would be better if he can provide us with a quick fix for the respective platform/browser. Others will not be harmed by this change :)

**Comment by varundey** [comment] 2018-09-13 09:31
I tested this on latest versions of Firefox, Firefox developer edition and Chrome both Mac and PC. Here are the steps to repro:

1. Click on Speakers, it'll open a dropdown
2. Click on Keynotes, the page will autoscroll and dropdown will get closed
3. Reclick on Speakers, you'll notice the blue background on Keynotes

**Comment by bhansa** [comment] 2018-09-13 09:57
The steps made this clear now, thanks for the quick fix.

**Comment by ananyo2012** [comment] 2018-09-13 15:02
Ah thanks a lot. Now I can reproduce it. Got it form the steps.

**Comment by ananyo2012** [comment] 2018-09-13 15:08
Closing this. Fixed in #186

**Closed by ananyo2012** 2018-09-13 15:08 UTC
